Dynamic Mapping Server Creation
gridsuite/dynamic-mapping-server pull request #1
Opened 2021-05-11 11:33 UTC by scalbertm

First commit, adding a minimal version of the server.
Includes:
- Mapping Storage and Creation
- Conversion of a Mapping to a groovy Script
- Scripts basic API

2021-05-11 14:34 UTC, jonenst commented on pom.xml
> +        <connection>scm:git:https://github.com/gridsuite/actions-server.git</connection>
mapping-server

2021-05-11 15:01 UTC, jonenst commented on pom.xml
> +            <artifactId>annotations</artifactId>
this one is probably a mistake ?

2021-05-11 15:09 UTC, jonenst commented on pom.xml
> +        <!-- needed for embedded-cassandra to download cassandra (only once) through authentified proxies -->
cassandra not used in this project

2021-05-11 15:14 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/MappingApplication.java
> +            public void addCorsMappings(CorsRegistry registry) {
why cors ? we don't use it in our other microservices. We reverse proxy the domain hosting the javascript instead

2021-05-11 15:19 UTC, jonenst commented
missing license header from many java files

2021-05-11 15:19 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/MappingApplication.java
> + * @author Geoffroy Jamgotchian <geoffroy.jamgotchian at rte-france.com>
please update the author information

2021-05-11 15:28 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/controller/MappingController.java
> +            @ApiResponse(code = 500, message = "The storage is down or a file with the same name already exists")})
is this a copy pasted error message ? if so, update it.

2021-05-11 15:54 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/repository/InstanceModelRepository.java
> +public interface InstanceModelRepository extends JpaRepository<InstanceModelEntity, UUID> {
Why UUID in the template arguments ? InstanceModelEntity has @Id on a String

2021-05-11 15:55 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/repository/InstanceModelRepository.java
> +    Optional<InstanceModelEntity> findById(String id);
Not needed if you have the correct template parameters?

2021-05-11 15:56 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/repository/MappingRepository.java
> +public interface MappingRepository extends JpaRepository<MappingEntity, UUID> {
why UUID in the template parameters, should be String ?

2021-05-11 16:04 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/service/implementation/ScriptServiceImpl.java
> +            HashMap<EquipmentType, ArrayList<Rule>> sortingRules = new HashMap<EquipmentType, ArrayList<Rule>>();
use java7's type inference: new HashMap<>, newArrayList<>

2021-05-11 16:07 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/service/implementation/ScriptServiceImpl.java
> +                EquipmentType ruleType = rule.getEquipmentType();
this whole blocks looks like collectors.groupingBy ?

2021-05-11 16:09 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/service/implementation/ScriptServiceImpl.java
> +            Optional<InstanceModelEntity> foundModel = instanceModelRepository.findById(rule.getMappedModel());
how many rules are expected here ? calling findById for each rule is going to be very long if there are many rules

2021-05-11 16:24 UTC, jonenst commented on src/main/resources/application.yaml
> +network-store-server:
network-store is not used ?

2021-05-11 16:26 UTC, jonenst commented on src/main/resources/application.yaml
> +dbName: postgres
the postgres db is reserved, you must set your name here. Like dynamicmapping

2021-05-11 16:42 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/model/FilterEntity.java
> +    // Value is the value casted to a string for persistence issue
maybe implement the same system as https://github.com/gridsuite/network-modification-server/blob/master/src/main/java/org/gridsuite/modification/server/entities/elementary/BooleanElementaryModificationEntity.java ?

2021-05-14 08:33 UTC, scalbertm commented on src/main/java/org/gridsuite/mapping/server/repository/InstanceModelRepository.java
> +    List<InstanceModelEntity> findAll();
Not needed for this POC but will be once instanciated models will be created user-side by merging parameters and dynamic models.

2021-05-14 10:05 UTC, scalbertm commented on src/main/java/org/gridsuite/mapping/server/model/RuleEntity.java
> +    @OneToMany(targetEntity = FilterEntity.class, mappedBy = "ruleId", cascade = CascadeType.ALL, orphanRemoval = true)
It works for the small sample I have tried.
There should not be calls from filter to rule so no need for bidirectional.
Used to be CollectionTable but could not make it work

2021-05-28 08:45 UTC, geofjamg requested changes
I didn't look at the code yet but some general comments:
 - every files need to copyright RTE and authorship in the class javadoc
 - Code coverage is very low, we usually require 80%
 -

2021-05-31 08:18 UTC, jonenst commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
remove this comment

2021-05-31 08:19 UTC, jonenst commented on pom.xml
> +            <version>2.2.9.RELEASE</version>
don't put the version here

2021-05-31 08:25 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/dto/filters/AbstractFilter.java
> +        AbstractFilter filter = new StringFilter();
don't create a new StringFilter here, instead put a default in the switch statement and throw an exception for unknown types

2021-05-31 08:29 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/repository/InstanceModelRepository.java
> +    List<InstanceModelEntity> findAll();
no I mean JpaRepository already has this method so redeclaring here has no effect

2021-05-31 08:36 UTC, jonenst commented on src/main/java/org/gridsuite/mapping/server/utils/Methods.java
> +        return array.stream().reduce("", (acc, element) -> {
use string joiner ? or at least a stringbuilder to avoid o(n²) performance

2021-06-03 15:48 UTC, jonenst approved these changes

2021-06-03 15:49 UTC, merged