use common conf
gridsuite/dynamic-mapping-server pull request #21
Opened 2021-11-12 10:15 UTC by jonenst

Signed-off-by: HARPER Jon <jon.harper87@gmail.com>

2021-11-12 15:29 UTC, laurgarn approved these changes

2021-11-15 10:48 UTC, sBouzols requested changes
not sure...

2021-11-15 10:48 UTC, sBouzols commented on src/main/resources/application.yaml
> -            entity_copy_observer: allow
this is not moved in the common conf. What should we do ?

2021-11-23 14:01 UTC, sBouzols commented on src/main/resources/application.yaml
> -            entity_copy_observer: allow
restored

2021-11-24 10:17 UTC, sBouzols approved these changes

2021-11-24 10:17 UTC, merged