dynamicModelId of the Automaton model must be unique in groovy file
gridsuite/dynamic-mapping-server pull request #43
Opened 2022-11-23 11:57 UTC by thangqp

dynamicModelId of the Automaton model must be unique (not the name of model) in groovy file => must be generated from model name and equipment id from automaton

2022-11-23 12:42 UTC, geofjamg requested changes

2022-11-23 12:42 UTC, geofjamg commented on src/main/java/org/gridsuite/mapping/server/utils/IAutomatonIdProvider.java
> +package org.gridsuite.mapping.server.utils;
License header

2022-11-23 12:42 UTC, geofjamg commented on src/main/java/org/gridsuite/mapping/server/utils/IAutomatonIdProvider.java
> +public interface IAutomatonIdProvider {
authorship

2022-11-23 12:42 UTC, geofjamg commented on src/main/java/org/gridsuite/mapping/server/utils/IAutomatonIdProvider.java
> +public interface IAutomatonIdProvider {
We usually do not use these kind of convention naming for interface like I.... We prefer AutomatonIdProvider -> AutomatonIdProviderImpl

2022-11-23 12:42 UTC, geofjamg commented on src/main/java/org/gridsuite/mapping/server/utils/IAutomatonIdProvider.java
> +    default String getId(AbstractAutomaton automaton) {
default should only be used for backward compatibility but not for implementing a method.

2022-11-23 16:40 UTC, thangqp commented on src/main/java/org/gridsuite/mapping/server/utils/IAutomatonIdProvider.java
> +    default String getId(AbstractAutomaton automaton) {
You are right!

2022-11-23 16:42 UTC, thangqp commented on src/main/java/org/gridsuite/mapping/server/utils/IAutomatonIdProvider.java
> +public interface IAutomatonIdProvider {
OK

2022-11-24 08:06 UTC, gautierbureau approved these changes

2022-11-24 08:20 UTC, thangqp commented on src/main/java/org/gridsuite/mapping/server/utils/IAutomatonIdProvider.java
> +package org.gridsuite.mapping.server.utils;
Added

2022-11-24 08:20 UTC, thangqp commented on src/main/java/org/gridsuite/mapping/server/utils/IAutomatonIdProvider.java
> +public interface IAutomatonIdProvider {
Added

2022-11-24 09:36 UTC, geofjamg approved these changes

2022-11-24 17:23 UTC, merged